server:
  servlet:
    session:
      timeout: PT2H 

spring:
  profiles:
    active: demo

  http:
    encoding:
      charset: UTF-8
      force: true
  #json日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mappers/*.xml,classpath:mappers/customize/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql